<table class="data" id="policies">
<thead>
<tr>
	<th></th>
	<th>Deontic</th>
	<th>Action</th>
	<th>Tasks</th>
</tr>
</thead>
<tbody>
<?php foreach($this->get('policies') as $id => $policy): ?>
<tr>
	<td><?php (print @++$c);?></td>
	<td><?php print $policy['deontic']; ?></td>
	<td><a class="btn btn-xs btn-default" href="#" onClick="acthelp('<?php print $policy['action'];?>')"><?php print $this->localName($policy['action']); ?>&nbsp;<i class="glyphicon glyphicon-info-sign"></i></a><br>
	<small><a href="<?php print $policy['action']; ?>" target="_action"><?php print $policy['action']; ?></a></small></td>
	<td><?php foreach($policy['tasks'] as $t): ?>
	<?php print $t;?>
	<?php endforeach;?></td>
</tr>
<?php endforeach;?>
</tbody>
</table>
<script>
$(document).ready(function(){
    $('#policies').DataTable();
});
</script>
<?php $this->partial('dnhelp', $this->getAll());?>