<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php print $this->get('title'); ?></title>
<link
	href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"
	rel="stylesheet">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<link
	href="<?php print route('resources','styles',array('id'=>'main'));?>"
	rel="stylesheet">
	
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	
<style>
@media (max-width: 600px) { #login { width: 100% ; }}
@media (min-width: 600px) and (max-width: 990px) { #login{ width: 50%; }}
@media (min-width: 990px) and (max-width: 1200px) { #login{ width:32%; }}
@media (min-width: 1200px) { #login{ width: 26%; }}
form div.input-group{ width: 100% !important; }
</style>
</head>
<body>

	<div class="container" id="login">
		<div class="contento-template">
			<div class="row high">
				<h1 class="col-lg-12 col-sm-12 brand">
					Policy Propagation - User Study<br/>
				</h1>
			</div>
			
			<div class="row ">
				<div class="col-lg-12">
				
			<div class="brand" style="font-size: 18px;margin-left:5px; "></div>
					<?php $this->partial('messages', array('messages'=> isset($_SESSION['messages']) ? $_SESSION['messages'] : array())); ?>
				</div>
			</div>
			<div class="row high">
				<div class="col-lg-12">
					<?php $this->partial($this->get('page'), $this->get('data', array())); ?>
				</div>
			</div>	
		</div>
	</div>
</body>
</html>
