<div  class="well">
<form method="post" style="margin:0px auto;" id="loginForm">		
	<div class="input-group">
		<label for="username">Username</label>
		<input class="form-control" id="username" name="username" type="text" value =""/>
	</div>
	<p></p>
	<div class="input-group">
		<label for="password">Password</label>
		<input class="form-control" id="password" name="password" type="password" value=""/>
	</div>
</form>

</div>


	<button class="btn btn-primary btn-lg justify" style="width:100%" type="button" onclick="$('#loginForm').submit();">Login</button>
	
