<?php 
$msg = $this->get('messages', array());
if(is_string($msg)){
	$msg = array('info'=>array($msg));
}
?>
<?php foreach($msg as $type => $ms): ?>
<?php foreach($ms as $m): ?>
<div class="alert alert-<?php print $type; ?>" role="alert">
<?php if($type == 'success'): ?>
<span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
<?php elseif($type == 'info'): ?>
<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
<?php elseif($type == 'warning'): ?>
<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
<?php elseif($type == 'danger'): ?>
<span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
<?php endif; ?>
<?php print $m; ?></div>
<?php endforeach; ?>
<?php endforeach; ?>
<?php /* XXX This shouldn't be here? */unset($_SESSION['messages']);?>
