<form method="POST" class="phaseactions">
<input type="hidden" name="id" value="<?php $this->spit('id'); ?>" />
<input type="hidden" name="controller" value="task" />
<?php if($this->get('phase')!=1): ?>
<div class="btn-group btn-group-lg">
<button  name="action" value="stepback"  class="btn btn-default btn-lg" type="submit"><i class="glyphicon glyphicon-arrow-left"></i>&nbsp;</button><?php endif;?><?php
$visited = $this->get('phasevisited');$descriptions=$this->get('descriptions'); 
foreach(array(1,2,3,4,5,6) as $ph):?><button 
	data-toggle="popover" 
	title="<?php print '#' . $ph; ?>" 
	data-content="<?php print $descriptions[$ph];?>" 
	name="action" 
	value="jumpto<?php print$ph;?>" 
	<?php if((!in_array($ph, $visited) || $ph == $this->get('phase')) && !($ph<$this->get('phase'))): print 'disabled="disabled"'; endif;?> 
	class="btn btn-<?php ($this->get('phase') == $ph)? print 'primary':print 'default' ;?> btn-lg" 
	type="submit"><?php print $ph;?></button>
	<?php if($this->get('phase')===4 && $ph == 4): ?>
<button onClick="return $('#submit_phase4').submit();" class="btn btn-danger btn-lg" type="button">Submit</button>
	<?php endif;?>
	<?php if($ph == 5 && ($this->get('phase') == 5 && $this->get('resolved', FALSE))): ?>
<button name="action" value="complete" class="btn btn-success btn-lg" type="submit"><i class="glyphicon glyphicon-ok"></i>&nbsp;Complete Task!</button>
	<?php endif;?>
	<?php endforeach;
?><?php if($this->get('phase')!=4 && $this->get('phase') < 5 ): 
?><button name="action" value="moveon" class="btn btn-<?php (!in_array($this->get('phase')+1, $visited))?print 'success':print 'default'; ?> btn-lg" type="submit"><i class="glyphicon glyphicon-arrow-right"></i></button>
<?php endif;?>
</div>
</form>
<script>
$(document).ready(function(){
	$('[data-toggle="popover"]').popover({trigger:'hover',placement: 'top'});
});
</script>