<p>Your objective is to become familiar with the process described in the
	following RapidMiner file.</p>
<p>
	<a
		href="<?php print route('task','download',array('id'=>$this->get('id')));?>"
		target="_rapidminerdownload">Download the file.</a>
</p>
<p>The file can be loaded in RapidMiner by doing "Import Process".</p>
<p>Explore the process together and discuss:</p>
<ul>
	<li>What is the nature of the input data. (How many input? Textual
		files, Arrays of numbers, A data table, ...?)</li>
	<li>What is the purposes of the system. (Perform analytics, Test a
		method, Clean the data, ...)</li>
	<li>What are the intermediary steps of the process.</li>
	<li>What happens to data during the process. (Is it copied,
		transformed, aggregated, split? They are data or metadata?)</li>
	<li>What is the nature of the ouput data? (How many output? Are they
		data or metadata?)</li>
</ul>
<p class="alert alert-warning"><i class="glyphicon glyphicon-warning-sign"></i>&nbsp;Beware! You don't need to understand the technical details of it, but you should
	understand what the process does to the data and why it is doing so.</p>
<p class="alert alert-success"><i class="glyphicon glyphicon-ok-sign"></i>&nbsp;When you are confident that you have a good udnerstanding of it, you
	can move to the next phase.</p>
