<p>These are data from the DataHub that are used as input for the process.</p>
<?php foreach($this->get('datasets', array()) as $dataset): ?>
<h3><?php print $dataset['title']; ?></h3>
<?php $this->partial('policies',$dataset['policies']);?>
<?php endforeach;?>
<p class="alert alert-success"><i class="glyphicon glyphicon-ok-sign"></i>&nbsp;When you are confident that you have a good understanding of the input datasets, you can move to the next phase.</p>
<?php $this->partial('dnhelp', $this->getAll());?>